### ISSUE TITLE
Preset fonts seem to break picker

### ISSUE THREAD

**Issue by ikaney** [zefoy/ngx-font-picker#13]
Using the font picker, if you use preset fonts and then open/close/open the font picker, the google fonts disappear?

**Comment by ikaney** [comment]
Just an update, I've worked around the issue by adding a boolean flag to the component (addedPresetFonts) and a check to stop it doing the operation twice:

private setDisplayedFontSource(): void {
    if (this.fpPresetFonts && this.fpPresetFonts.length && !this.addedPresetFonts) {
      this.setCurrentFonts(this.getPresetFonts());
      this.addedPresetFonts = true;
    } else {
      this.setCurrentFonts(this.googleFonts);
    }
  }

**Comment by sconix** [comment]
Hmm I am not seeing this in the example app nor in our application that uses this library. Do you have some ngIf's in play or something that could cause the whole component to reset?

**Comment by ikaney** [comment]
It’s actually reproducible on the example demo. Turn preset fonts on open the picker, close and then reopen. The bottom Google fonts will mirror the preset ones.

**Comment by ikaney** [comment]
Awesome, thank you!
