### ISSUE TITLE
fpPosition 'top' fails after first display

### ISSUE THREAD

**Issue by rohanrichards** [zefoy/ngx-font-picker#14]
When using `[fpPosition]="'top'"` after opening the widget for the first time it will no longer display above the parent element.

This can easily be verified on StackBlitz:
https://stackblitz.com/github/vbwigowk
https://vbwigowk.github.stackblitz.io

**Comment by sconix** [comment]
So it seems, I will release a fix.

**Comment by sconix** [comment]
This is fixed in 7.2.0 that I just released. Thanks for reporting this.
