### ISSUE TITLE
Default font Style and Font Size dropdown couldnot be open while loading Component

### ISSUE THREAD

**Issue by sumits5** [zefoy/ngx-font-picker#15]
Default font Style and Font Size dropdown couldnot be open while loading Component. I used the fpFontStyle and fpFontSize directive but I checked the library and by default component property selectedfont is false and that we can not set while loading.

**Comment by sconix** [comment]
I do not follow you so could you try to elaborate a bit. What do you mean with while loading component?

**Comment by sumits5** [comment]
I cannot by default set the font style(bold, italic, and so on) and font size on the component initialization ( Page loading ) even though i can set the font family programmatically (example : Roboto etc.) and i guess it is due to the property selectedfont is set to false by default in the Fontpicker component. it is setted in the 'onSelectFont ' method of the fontpicker component

Find the below image where I have highlighted selectedFont property which is by default false.

![fontpicker](https://user-images.githubusercontent.com/47789300/53174030-73821f80-35ae-11e9-8d66-43ea6ce76538.PNG)

**Comment by sconix** [comment]
I am still having bit of trouble :) Yes default selectedFont is false, but you can pass in the selected font for the dialog via the fpFontPicker input. Or are you saying that it wont work?

There needs to be a font selected for the size / style controls to be shown.

**Comment by sconix** [comment]
I did a quick test and it indeed does seem like its not working. I will release a fix at the latest on monday.

**Comment by sconix** [comment]
Should be fixed in 7.3.1 if not let me know.
