### ISSUE TITLE
Not an issue - Just need enhancement

### ISSUE THREAD

**Issue by sumits5** [zefoy/ngx-font-picker#17]
We want to display only preset fonts in the font picker dialogue box or you can say only specific fonts. But I looked documentation as well as code repository and there is no option to restrict google fonts also that is getting set as currentfonts variable in the font-picker component.

**Comment by sconix** [comment]
I can consider adding this for 8.0.0 version, until then PR's are accepted or you just need to hide the google fonts with styles. Not sure what you mean by set as currentfonts variable.

**Comment by sumits5** [comment]
Yes I just want to avoid google fonts.so, then I will not require google api key beacuse we will be displaying only preset font in the dialogue box which are not associated with Google fonts.

**Comment by sconix** [comment]
I will do it so that if the apiKey is not provided it won't try to load/use Google fonts. And this will be added for 8.0.0 release which is out at the latest when Angular 8 is out. If I have time before I will make the release earlier but at the moment really busy.

**Comment by sumits5** [comment]
Yes Thank you, But If you could do it before angular 8 release that would be great for us to use this feature for our application. ( if possible :+1:  )
