### ISSUE TITLE
Possibility to filter the fonts

### ISSUE THREAD

**Issue by mmrzk** [zefoy/ngx-font-picker#18]
Hello there and thanks for the great lib!
I'd like to ask if there is any possibility to filter the fonts to have only those I'm interested in?
It would be nice if we could filter them by family, so that a method/function that filters them could have an array with strings such as 
`['family1', 'family2', 'family3']`

**Comment by sconix** [comment]
That sounds like a good idea, I do not promise anything but will try to add such feature for 9.1.0. Until that PR's are welcome.

**Comment by mmrzk** [comment]
Hello again, it took me some time, I've submitted the PR https://github.com/zefoy/ngx-font-picker/pull/30

**Comment by LukasKlement** [comment]
I've added a new PR to address this issue.

I'd argue the feature is important, specifically in cases where you are using this component to choose fonts for a document that is rendered server-side (e.g. a PDF). In that case, you may not want to give users all Google Fonts up for selection, but only a subset of fonts for which you have a server-side rendering licence and/or which are installed on your server.
