### ISSUE TITLE
Warning on CommonJS or AMD dependencies after upgrading to Angular 10

### ISSUE THREAD

**Issue by Sparker73** [zefoy/ngx-font-picker#24]
Hello:
I don't know if this is a question, an enhancement or just a concern, anyhow, I was happily using this amazing library as you can see in the attached screenshot and I noticed in the Javascript console the following warning:

.../node_modules/ngx-font-picker/fesm2015/ngx-font-picker.js depends on 'webfontloader'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

It happened after upgrading to Angular 10, everything works great but it looks like the AOT compilation is starting to warn about CommonJS and AMD dependencies. I don't know which the implications would be in a near future. It sounds like the font picker uses a javascript module called `webfontloader` which is distributed as CommonJS module or AMD module.

What the screenshot is about? It is a Real Estate Platform where users can create a CMS-like custom page but focusing of the features of a property, market, agent or broker and certainly they will need to pick a font that goes with their company identity, this is a piece of the admin side. Wonderful job with this library by the way.

![warning-on-commonjs](https://user-images.githubusercontent.com/9856898/99566906-17bb1500-2993-11eb-92e7-3f6a102a16a7.png)

**Comment by sconix** [comment]
CLI just added the warning, but there is nothing to do for it due to the webfontloader dependency. Anyway its just a warning.

**Comment by Sparker73** [comment]
Comprendido! Thanks. I will close the issue.
