### ISSUE TITLE
 Property 'getStyles' is missing in type 'FontInterface' but required in type 'Font'.

### ISSUE THREAD

**Issue by hinalshah91** [zefoy/ngx-font-picker#25]
I am using the following code in my HTML.
```
<div
            [(fontPicker)]="font"
            [fpWidth]="'320px'"
            [fpPosition]="'bottom'"
          >
            Click to open the font picker
</div>
```

Following is my package.json.
`{
  "name": "wiz-merchant-manager",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "startssl": "ng serve --ssl --ssl-key certs/privkey1.pem  --ssl-cert certs/fullchain1.pem --host local.dev.wizshops.com",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "locales": "ngx-translate-extract -i ./src -o src/assets/locale/{ar,en}.json --sort --format namespaced-json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.0.0",
    "@angular/cdk": "^11.0.0",
    "@angular/common": "~11.0.0",
    "@angular/compiler": "~11.0.0",
    "@angular/core": "~11.0.0",
    "@angular/forms": "~11.0.0",
    "@angular/localize": "~11.0.0",
    "@angular/material": "^11.0.0",
    "@angular/platform-browser": "~11.0.0",
    "@angular/platform-browser-dynamic": "~11.0.0",
    "@angular/router": "~11.0.0",
    "@biesbjerg/ngx-translate-extract": "^7.0.3",
    "@biesbjerg/ngx-translate-extract-marker": "^1.0.0",
    "@fortawesome/fontawesome-free": "^5.15.1",
    "@ng-bootstrap/ng-bootstrap": "^8.0.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "angular-cookies": "~1.8.2",
    "bootstrap": "^4.5.3",
    "chart.js": "^2.9.4",
    "jsbarcode": "^3.6.0",
    "ng-cookies": "^1.0.2",
    "ng2-charts": "^2.4.2",
    "ngx-barcode": "^0.3.0",
    "ngx-color-picker": "^10.1.0",
    "ngx-cookie": "^5.0.0",
    "ngx-font-picker": "^11.0.0",
    "ngx-print": "^1.2.0-beta.5",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.1",
    "@angular/cli": "~11.0.1",
    "@angular/compiler-cli": "~11.0.0",
    "@types/angular-cookies": "^1.8.0",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  },
  "peerDependencies": {
    "@angular/core": "^11.0.3",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  }
}
`

In my theme.module.ts file, I have added the following code:
```
import { FontPickerModule, FONT_PICKER_CONFIG, FontPickerConfigInterface } from 'ngx-font-picker';

const DEFAULT_FONT_PICKER_CONFIG: FontPickerConfigInterface = {
  // Change this to your Google API key
  apiKey: environment.googleAPIkey
};

 imports: [
    FontPickerModule
  ],

providers: [
    {
      provide: FONT_PICKER_CONFIG,
      useValue: DEFAULT_FONT_PICKER_CONFIG
    }
  ]
```

But when I run the application using 'npm start', I get the following error:
Property 'getStyles' is missing in type 'FontInterface' but required in type 'Font'.

I tried adding the import code in app.module.ts file as well, but I still get the same error. 

Can you please help?

**Comment by sconix** [comment]
Not sure why I can not get the compiler spew out that error, but there does seem to be an error with the Font interface. I release 11.0.1 that has a fix for this.
