### ISSUE TITLE
NPM package does not have the right ngx-scrollbar version as dependency

### ISSUE THREAD

**Issue by Rugshtyne** [zefoy/ngx-font-picker#37]
Hello, I've faced multiple issues after upgrading my whole code to Angular v13 but basically came down to the thing that ngx-font-picker has ngx-scrollbar as dependency which is listed with version incompatible with Angular v13. 

I see that here in Github the dependency is listed correctly, having version ^9.0.0 which supports Angular v13. However, when installing via npm for some reason the ngx-scrollbar is listed as dependency with version ^7.x.

![image](https://user-images.githubusercontent.com/36242162/157229892-1aeb4f46-ef42-4747-b60c-d35fd7d12ee2.png)

Can you check what's the issue here?

**Comment by sconix** [comment]
Will be fixed in the next release
