### ISSUE TITLE
Incompatible with Angular 16 | Replace export ReflectiveInjector

### ISSUE THREAD

**Issue by LukasKlement** [zefoy/ngx-font-picker#49]
The ReflectiveInjector was removed from @angular/core, leading to this error when building:

export 'ReflectiveInjector' (imported as 'ReflectiveInjector') was not found in '@angular/core' 

To make the library compatible with Angular 16, this dependency should be removed/replaced.

**Comment by dodos90** [comment]
I opened the following PR for this specific issue : https://github.com/zefoy/ngx-font-picker/pull/52

**Comment by sconix** [comment]
Will release new version soonish, in two weeks at most

**Comment by LukasKlement** [comment]
I've opened a PR to bump the dependency versions. I haven't tested it with Angular>16, and hence I required that version. Though, I'd guess, you will want to decide the desired backwards compatibility of this library in a different way.

**Comment by sconix** [comment]
I will make a new Angular 16 supported release after one week when I am back from my holiday trip, sorry for the delay.

**Comment by LukasKlement** [comment]
Thanks, it works like a charm under Angular 16 + Angular 17.
