### ISSUE TITLE
perfect-scrollbar issue

### ISSUE THREAD

**Issue by urvesh21** [zefoy/ngx-font-picker#7]
"perfect-scrollbar.component.js:132 Deprecated function, update needs to be called through directiveRef!"

I am getting this warning message in my angular2 website and I am unable to scroll the font list inside font list container.
Please let me know how to fix this.

**Comment by sconix** [comment]
The warning should not have any effect on the scrolling, but there has been some other changes that can have an effect. You can always install the previous version of ngx-perfect-scrollbar, but I can do an update tomorrow for this library so that it works with the latest perfect-scrollbar.

**Comment by sconix** [comment]
I will release 4.1.0 today which should work with the latest ngx-perfect-scrollbar library. Let me know if you still have problems with the 4.1.0.

**Comment by urvesh21** [comment]
Thanks !!! Problem solved.
