### ISSUE TITLE
ngx-font-picker.js not found 

### ISSUE THREAD

**Issue by nourissam** [zefoy/ngx-font-picker#8]
Hello
i m using angular 2 seed .i wanna implement your  framework .i follow the steps but it give me an error
![image](https://user-images.githubusercontent.com/6942024/31096145-1e7f8d86-a7b3-11e7-90f8-c205e694a8e1.png)

**Comment by sconix** [comment]
I am not familiar with angular 2 seed. If it still uses Angular 2 then this library wont work, you need to have Angular 4. The example app has a SystemJS configuration which you can see how to configure SystemJS. If you are new to Angular I recommend that you go with angular-cli which wont need any configuration.
