### ISSUE TITLE
 perfect-scrollbar.module.d.ts has no exported member 'OpaqueToken'.`

### ISSUE THREAD

**Issue by doczoidberg** [zefoy/ngx-font-picker#9]
I want to use the font picker in a angular 5 app (generated with angular cli 1.5) but getting the error:

`ERROR in node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.module.d.ts(1,31): error TS2305: Module '".../node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.`

**Comment by sconix** [comment]
There is no Angular 5 version out of that library yet, I am stuck with waiting for new release of perfect-scrollbar, as soon as its out there will be Angular 5 supported version of this and ngx-perfect-scrollbar.

The fixes area already merged to perfect-scrollbar so I am only waiting for the library owner to make a new release.

**Comment by sconix** [comment]
I am releasing 5.0.0-0 (pre-release) version under @next tag today. So you could give it a try, it should work with Angular 5. Official 5.0.0 release will follow quite soon.

**Comment by sconix** [comment]
Actually I will just release 5.0.0 directly at the latest on this Friday, hopefully already tomorrow.

**Comment by sconix** [comment]
5.0.0 is now out and uses the latest perfect-scrollbar so should now work perfectly with Angular 5.
